### ISSUE TITLE
rename ps_read_tables?

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/poissqlite#12]
thinking ps_read_tables should be renamed to ps_load_tables, or ps_load_sqlite to be consistent with suite of loading functions (ps_load_csv, ps_load_excel, ps_load_spatial, ps_load_gdb).

Also, wondering if these 'loading' functions should all be in same package (poisdata?) or even a new package (poisload?). Currently, spread across poissqlite, poisdata, poisspatial.

I think these functions bundled together could be a useful package for the public, although I realise there's not much incentive to spend time working on documentation/promotion.

**Comment by sebdalgarno** [comment]
could take a quick look at how many historical repos would have to be updated...

**Comment by joethorley** [comment]
yes I agree with renaming. - I've just added ps_load_tables and deprecated ps_read_tables.

**Comment by joethorley** [comment]
Although similar in name and function I'm not sure if bundling in a single package makes sense because 1) they may rely on internal functions in their respective packages 2) even if they use external functions in the original packages they would still require their original packages to be loaded which kind of makes the bundling redundant. and 3) poispkgs ensure all are loaded and in the search path.

**Comment by sebdalgarno** [comment]
yes all points raised make sense to me...agree that no need for separate package.  I'll close this.
